### PR TITLE
Fix compatibility with Python 3

### PR DESCRIPTION
**Pull request by disrupted**

### CODE REVIEW

**Comment by disrupted** [comment]
pinging @rmoff for review

**Comment by rmoff** [comment]
@disrupted happy to merge this but shouldn't the PR be to the upstream repo https://github.com/mapr-demos/gess ?

**Comment by disrupted** [comment]
> @disrupted happy to merge this but shouldn't the PR be to the upstream repo https://github.com/mapr-demos/gess ?

I actually haven't looked into the upstream repo before, but seeing as the last commit is over 9 years ago I am not sure it would get any attention there. Do you think it still makes sense to transfer it there?

I was mainly hoping to restore functionality for the Kafka demos that use this project, now that Python 2.7 is no longer around.

**Comment by rmoff** [comment]
I've merged the PR - thanks for doing it. 

@mhausenblas looks like the owner of the original, maybe he can comment on whether he'd want the change pushed upstream too.

**Pull request merged**
